worker_processes auto;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    keepalive_timeout 65;

    upstream services_manager { server services-manager:8080; }
    upstream robot_recycling  { server robot-recycling:5000; }
    upstream sudo_manager     { server sudo-manager:8081; }
    upstream status_dashboard { server status-dashboard:8082; }
    upstream token_manager    { server token-manager:8083; }
    upstream license_manager  { server license-manager:8084; }
    upstream nexus_connector  { server nexus-connector:8085; }
    upstream interstellar_wealth { server interstellar-wealth:8087; }

    server {
        listen 80;
        server_name _;

        location /nexus/ {
            proxy_pass http://nexus_connector/;
            proxy_set_header Host $host;
        }

        location /interstellar-wealth/ {
            proxy_pass http://interstellar_wealth/;
            proxy_set_header Host $host;
        }

        location /robot-recycling/ {
            proxy_pass http://robot_recycling/;
            proxy_set_header Host $host;
        }

        location /sudo-manager/ {
            proxy_pass http://sudo_manager/;
            proxy_set_header Host $host;
        }

        location /status-dashboard/ {
            proxy_pass http://status_dashboard/;
            proxy_set_header Host $host;
        }

        location /token-manager/ {
            proxy_pass http://token_manager/;
            proxy_set_header Host $host;
        }

        location /license-manager/ {
            proxy_pass http://license_manager/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://services_manager/;
            proxy_set_header Host $host;
        }
    }
}
